### ISSUE TITLE
Controle de estoque WordPress

### ISSUE THREAD

**Issue by byandressalopes** [ProBeta12/Kahxapu-komo#14]
> Conjunto de ferramentas e plugins que permitem aos administradores de lojas virtuais acompanhar e gerenciar a quantidade de produtos disponíveis em estoque. 

> Essa funcionalidade é essencial para evitar a venda de produtos que estão indisponíveis e otimizar processos logísticos.

**Comment by MarceloSwap** [comment]
### **A tarefa já está concluída pelo fato de termos usado o Wordpress!**
Na primeira imagem mostra todos os produtos, na segunda a quantidade em estoque que pode ser definida ao cadastrar o produto.
![Image](https://github.com/user-attachments/assets/26896040-e8a5-48fb-bf20-206845ddc196)
![Image](https://github.com/user-attachments/assets/8710d609-7472-4e53-96cf-182466bc75d8)
