### ISSUE TITLE
Depoimento dos artesãos

### ISSUE THREAD

**Issue by byandressalopes** [ProBeta12/Kahxapu-komo#15]
Ao compartilhar suas histórias, técnicas e inspirações, esses artistas não apenas enriquecem nosso conhecimento sobre a cultura indígena Wai Wai, mas também contribuem para a valorização de suas artes e para a preservação de suas tradições.

### O que incluir nos depoimentos:

- **Histórias de vida**: Como o artesão aprendeu sua arte? Quais são suas principais inspirações?
- **Processos criativos**: Quais materiais são utilizados? Quais são as técnicas tradicionais?
- **Significado cultural**: Qual o significado da arte para a comunidade? Como os artesões querem que sua arte seja vista?
- **Desafios e conquistas**: Quais são os desafios enfrentados pelos artesãos? Quais são suas maiores conquistas?

**Comment by Girleane19** [comment]
OI.

**Comment by Girleane19** [comment]
[Depoimento dos Artesãos.docx](https://github.com/user-attachments/files/16606446/Depoimento.dos.Artesaos.docx)

**Comment by Girleane19** [comment]
[Uploading Depoimento dos Artesãos Atualiazado.docx…]()
