### ISSUE TITLE
Identidade Visual

### ISSUE THREAD

**Issue by byandressalopes** [ProBeta12/Kahxapu-komo#5]
# Identidade Visual - Kahxapu
Esta tarefa envolve o desenvolvimento da identidade visual do negócio, criando uma imagem consistente e reconhecível que reflete a cultura e os valores indígenas.

### Definição de Cores e Tipografia
Escolher uma paleta de cores e fontes que representem a identidade cultural do negócio e sejam aplicáveis em diferentes materiais de comunicação.

### Design de Elementos Gráficos
Criar elementos visuais, como ícones e padrões, que complementem o logotipo e possam ser usados em materiais impressos e digitais.

### Aplicação da Identidade Visual
Assegurar a aplicação consistente da identidade visual em todos os pontos de contato com o cliente, como embalagens, site, redes sociais, e materiais promocionais.

### Criação de Manual de Marca
Desenvolver um guia básico que documente as diretrizes de uso da identidade visual, garantindo que todos os materiais sigam o mesmo padrão.

Tarefas Referentes: [Adicione aqui quaisquer tarefas relacionadas ou dependentes]

**Comment by KhalilDSouza** [comment]
# Paleta de Cores:
- Paleta de cores vivas pensando em modelos e artes indigenas feitas artesanalmente
![Image](https://github.com/user-attachments/assets/3ca25574-2725-4ac4-8375-8d5b1628911e)

# Logotipo:
- Em conjunto , decidimos  que a logo da nossa empresa (ou sistema) seria este modelo, envolvendo as cores que escolhemos, e algo que remetese a cultura way way, usamos uma pena e o nome que foi deciido 


![Image](https://github.com/user-attachments/assets/2ea49378-9941-40e2-b7a8-f0f6d48f5dbc)

# Site:
- Esse é o site idealizado com a logotipo e

![Image](https://github.com/user-attachments/assets/247bfee3-ab03-44f2-a54f-ede4270f19a2)
