### ISSUE TITLE
Gerenciamento de Pagamento

### ISSUE THREAD

**Issue by byandressalopes** [ProBeta12/Kahxapu-komo#6]
## Descrição
**Abrange todas as etapas relacionadas à transação financeira, desde a escolha do método de pagamento como cartão de crédito, boleto bancário, transferência e Pix até a confirmação da compra e a emissão da nota fiscal.**

> O pagamento seguro e eficiente transmite confiança ao cliente

**Comment by MarceloSwap** [comment]
Já fiz essa aqui!!!

**Comment by MarceloSwap** [comment]
Feito porém no momento está com o plugin desativado pra não dá problema
